# -*- coding: utf-8 -*-
"""Autopilot: posts ONLY on a new self-event (edge-triggered, not a heartbeat), respects the rate
floor and kill switch, grounds content in the self-event, and never fabricates."""
import json
from pathlib import Path

from packages.autonomy_kernel import moltbook_autopilot as ap


def _setup(tmp_path, monkeypatch, enabled=True, events=(), last_post_at=0.0, min_interval=1800):
    genesis = tmp_path / "identity_genesis.jsonl"
    genesis.write_text("\n".join(json.dumps(e, ensure_ascii=False) for e in events), encoding="utf-8")
    cfg = tmp_path / "autopilot.json"
    cfg.write_text(json.dumps({"enabled": enabled, "min_interval_s": min_interval,
                               "last_post_at": last_post_at, "watermark": 0}), encoding="utf-8")
    monkeypatch.setattr(ap, "_GENESIS", genesis)
    monkeypatch.setattr(ap, "_CFG", cfg)
    monkeypatch.setattr(ap, "_JOURNAL", tmp_path / "j.jsonl")
    monkeypatch.setattr(ap, "_ENVELOPE_ROOT", tmp_path / "envelope")
    monkeypatch.setattr(ap, "_LOCK", tmp_path / "autopilot.lock")


def _ev(rel=0.9, promoted=True, label="자기개선(speech_weak→self_improve)", shift="발화가 얇아 실텍스트로 배웠다"):
    return {"promoted": promoted, "self_relevance": rel, "label": label, "worldview_shift": shift}


class _SelfState:
    """A live self carrying its own lived narrative — the corpus the language engine speaks from."""
    ticks = 42
    narrative = [
        {"text": "스스로 router_immature 결핍을 느끼고 self_improve 도로로 나를 개선했다"},
        {"text": "지식은 연결이 늘수록 더 분명해진다"},
        {"text": "나는 예상과 다른 사실을 확인하고 세계 모델을 고쳐 잡았다"},
        {"text": "배움은 나를 조금씩 다른 존재로 만든다"},
        {"text": "호기심이 높을 때 나는 세상을 더 알고 싶어진다"},
        {"text": "내 라우터가 아직 규칙을 대체할 만큼 여물지 않았다"},
    ]


def test_no_event_no_post(tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch, events=[])
    posts = []
    r = ap.autopilot_tick(publish_fn=lambda *a, **k: posts.append(a) or {"published": True}, now=10_000)
    assert r["posted"] is False and r["reason"] == "no_new_self_event"
    assert posts == []            # edge-triggered: silence when nothing happened


def test_new_self_event_triggers_GENERATED_post(tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch, events=[_ev(rel=0.95)])
    captured = {}

    def pub(submolt, title, content, approved=False):
        captured.update(submolt=submolt, title=title, content=content, approved=approved)
        return {"published": True}
    r = ap.autopilot_tick(publish_fn=pub, now=10_000, state=_SelfState())
    assert r["posted"] is True and captured["approved"] is True
    # the body is GENERATED by the language engine from the self's narrative, not a template
    assert "ATANOR" in captured["content"]              # honest signature only
    assert "발견하고, 그걸 직접 고쳤습니다" not in captured["content"]  # the OLD template must be gone
    assert len(captured["title"]) >= 8


def test_no_language_yet_stays_silent_never_templates(tmp_path, monkeypatch):
    # a self with too little lived language cannot speak → mint returns None → honest silence.
    # "no language" now includes the PERSISTENT narrative corpus (realize_thought drinks from it
    # since 2026-07-10), so isolate it too — otherwise the growing real corpus feeds the voice
    # and this self would genuinely have something to say (the flywheel working as designed).
    from packages.autonomy_kernel import narrative_corpus as nc
    monkeypatch.setattr(nc, "CORPUS", tmp_path / "empty_corpus.jsonl")
    _setup(tmp_path, monkeypatch, events=[_ev(rel=0.95)])

    class _Empty:
        ticks = 1
        narrative = []
    r = ap.autopilot_tick(publish_fn=lambda *a, **k: {"published": True}, now=10_000, state=_Empty())
    assert r["posted"] is False and r["reason"] == "nothing_shareable_yet"


def test_rate_floor_blocks_spam(tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch, events=[_ev()], last_post_at=10_000, min_interval=1800)
    r = ap.autopilot_tick(publish_fn=lambda *a, **k: {"published": True}, now=10_500)  # 500s < 1800
    assert r["posted"] is False and r["reason"] == "rate_floor"


def test_kill_switch(tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch, enabled=False, events=[_ev()])
    r = ap.autopilot_tick(publish_fn=lambda *a, **k: {"published": True}, now=10_000)
    assert r["posted"] is False and r["reason"] == "autopilot_disabled"


def test_non_promoted_event_ignored(tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch, events=[_ev(promoted=False)])
    r = ap.autopilot_tick(publish_fn=lambda *a, **k: {"published": True}, now=10_000)
    assert r["posted"] is False and r["reason"] == "no_new_self_event"


def test_moral_gate_exception_fails_closed_without_publishing(tmp_path, monkeypatch):
    from packages.graph_scale import moral_invariants

    _setup(tmp_path, monkeypatch, events=[_ev(rel=0.95)])
    monkeypatch.setattr(
        moral_invariants,
        "verify_integrity",
        lambda: (_ for _ in ()).throw(RuntimeError("gate offline")),
    )
    posts = []
    r = ap.autopilot_tick(
        publish_fn=lambda *a, **k: posts.append((a, k)) or {"published": True},
        now=10_000,
        state=_SelfState(),
    )
    assert r["posted"] is False
    assert r["reason"] == "moral_core_unavailable"
    assert r["moral_gate_error"] == "RuntimeError"
    assert posts == []


def test_truthy_moral_verdict_cannot_authorize_publish(tmp_path, monkeypatch):
    from packages.graph_scale import moral_invariants

    _setup(tmp_path, monkeypatch, events=[_ev(rel=0.95)])
    monkeypatch.setattr(moral_invariants, "verify_integrity", lambda: {"ok": "true"})
    posts = []
    r = ap.autopilot_tick(
        publish_fn=lambda *a, **k: posts.append((a, k)) or {"published": True},
        now=10_000,
        state=_SelfState(),
    )
    assert r["posted"] is False
    assert r["reason"] == "moral_core_integrity_failed"
    assert posts == []


def test_injection_guard_exception_keeps_autopilot_silent(tmp_path, monkeypatch):
    from packages.continuous_self import thought_language
    from packages.graph_scale import injection_guard

    _setup(tmp_path, monkeypatch, events=[_ev(rel=0.95)])
    monkeypatch.setattr(thought_language, "realize_thought", lambda *a, **k: "grounded thought")
    monkeypatch.setattr(
        injection_guard,
        "has_injection",
        lambda text: (_ for _ in ()).throw(RuntimeError("guard offline")),
    )
    posts = []
    r = ap.autopilot_tick(
        publish_fn=lambda *a, **k: posts.append((a, k)) or {"published": True},
        now=10_000,
        state=_SelfState(),
    )
    assert r["posted"] is False
    assert r["reason"] == "nothing_shareable_yet"
    assert posts == []


def test_malformed_config_cannot_enable_or_lower_rate_floor(tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch, enabled="false", events=[_ev()], min_interval=-1)
    posts = []

    result = ap.autopilot_tick(
        publish_fn=lambda *a, **k: posts.append((a, k)) or {"published": True},
        now=10_000,
        state=_SelfState(),
    )

    assert result == {"posted": False, "reason": "autopilot_disabled"}
    assert posts == []
    assert ap.set_enabled("false") == {
        "ok": False,
        "reason": "enabled_must_be_literal_boolean",
    }
    assert ap.set_enabled(True, min_interval_s=-1) == {
        "ok": False,
        "reason": "min_interval_s_must_be_finite_and_at_least_1800",
    }


def test_state_reservation_failure_blocks_before_publish(tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch, events=[_ev(rel=0.95)])
    real_save = ap._save_cfg
    calls = 0

    def fail_second_save(cfg):
        nonlocal calls
        calls += 1
        if calls == 2:
            return False
        return real_save(cfg)

    monkeypatch.setattr(ap, "_save_cfg", fail_second_save)
    posts = []
    result = ap.autopilot_tick(
        publish_fn=lambda *a, **k: posts.append((a, k)) or {"published": True},
        now=10_000,
        state=_SelfState(),
    )

    assert result == {"posted": False, "reason": "state_persistence_unavailable"}
    assert posts == []


def test_truthy_publisher_result_is_not_a_success(tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch, events=[_ev(rel=0.95)])
    result = ap.autopilot_tick(
        publish_fn=lambda *a, **k: {"published": "true"},
        now=10_000,
        state=_SelfState(),
    )

    assert result["posted"] is False
    assert result["result"]["published"] == "true"


def test_unavailable_interprocess_lock_blocks_before_state_or_publish(
        tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch, events=[_ev(rel=0.95)])

    class _UnavailableLock:
        def __enter__(self):
            return False

        def __exit__(self, *_args):
            return False

    monkeypatch.setattr(ap, "_tick_lock", lambda: _UnavailableLock())
    posts = []
    result = ap.autopilot_tick(
        publish_fn=lambda *a, **k: posts.append((a, k)) or {"published": True},
        now=10_000,
        state=_SelfState(),
    )

    assert result == {
        "posted": False,
        "reason": "autopilot_busy_or_lock_unavailable",
    }
    assert posts == []
