# -*- coding: utf-8 -*-
"""Track F / F0 — ingest human dialogue datasets into the register corpus + grounded-realizer pairs.

Owner proposed DailyDialog, OpenSubtitles, MultiWOZ, PersonaChat, Topical-Chat, Wizard-of-Wikipedia,
UltraChat. They fill the MEASURED bottleneck (dialogue register absence, 0.60 plateau). But two
filters are BINDING and encoded here as data, not applied by hand at ingest time:

  1. No-LLM: a dataset GENERATED BY AN LLM is forbidden — training on it distils that LLM, the exact
     opposite of No-LLM. UltraChat (ChatGPT-generated) is REJECTED for this reason. Any future
     synthetic/LLM chat set is rejected by the same rule.
  2. License-clean: copyright-encumbered redistribution (raw film subtitles) is quarantined; non-
     commercial (NC) sets are usable for research but FLAGGED so a commercial ship re-checks them.

Adopted sets normalise to two streams:
  * register lines  {source, register, text}                      — teach dialogue FORM
  * grounded pairs  {source, knowledge, history, response}        — extend bones->text to grounded
                                                                    CONVERSATION (WoW / Topical-Chat)

Parsers are pure and unit-tested on synthetic samples; run against locally-downloaded raw files.
  python scripts/f0_ingest_dialogue.py --src dailydialog --path <file>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT_REG = REPO / "data" / "graph_scale" / "dialogue_register.jsonl"
OUT_GND = REPO / "data" / "graph_scale" / "dialogue_grounded.jsonl"

# The verdict, as data. adopt=True flows into the corpus; adopt=False is refused at ingest.
SOURCES: dict[str, dict] = {
    "wizard_of_wikipedia": {"adopt": True, "register": "grounded-chat", "grounded": True,
                            "license": "CC-BY-SA (Wikipedia-derived)",
                            "note": "BEST FIT — each wizard turn grounds a fluent reply in a Wikipedia sentence = our realizer task in dialogue form"},
    "topical_chat":        {"adopt": True, "register": "grounded-chat", "grounded": True,
                            "license": "CDLA-Sharing (Amazon)", "note": "knowledge-grounded open chat"},
    "multiwoz":            {"adopt": True, "register": "task-assistant", "grounded": False,
                            "license": "MIT-style", "note": "task-oriented assistant register"},
    "persona_chat":        {"adopt": True, "register": "persona-chat", "grounded": False,
                            "license": "MIT (ParlAI)", "note": "persona-consistent casual chat"},
    "dailydialog":         {"adopt": True, "register": "daily-social", "grounded": False,
                            "license": "CC BY-NC-SA 4.0", "flag": "NON-COMMERCIAL — re-check before a commercial ship",
                            "note": "clean human daily conversation"},
    "opensubtitles":       {"adopt": False, "register": "film-dialogue", "grounded": False,
                            "license": "copyrighted subtitles", "note": "QUARANTINE — redistribution/copyright unclear + noisy; skip for the license-clean gate"},
    "ultrachat":           {"adopt": False, "register": "synthetic-chat", "grounded": False,
                            "license": "MIT (data) BUT ChatGPT-GENERATED",
                            "note": "REJECTED — training on LLM output = distilling an LLM = No-LLM violation"},
    "wiki_talk":           {"adopt": True, "register": "collab-talk", "grounded": False,
                            "license": "CC BY-SA (Wikipedia talk pages, ConvoKit)",
                            "note": "real human editor conversation — turn-taking, self-correction, 1st-person stance (G2)"},
    "stackexchange":       {"adopt": True, "register": "qa-help", "grounded": False,
                            "license": "CC BY-SA (Stack Exchange data dump)",
                            "note": "real human question->answer help register (ELL site = plain English)"},
}


def _strip_html(s: str) -> str:
    import re as _re
    # DECODE entities first, THEN strip tags — SE stores markup as encoded entities inside the XML
    # attribute (&lt;p&gt;), so stripping before decoding leaves the decoded <p> behind (measured).
    s = (s or "").replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", '"') \
        .replace("&#39;", "'").replace("&#xA;", " ").replace("&#xD;", " ")
    s = _re.sub(r"<[^>]+>", " ", s)
    s = s.replace("&amp;", "&")                      # ampersand last, so &amp;lt; can't re-form a tag
    return " ".join(s.split())


def parse_wiki_talk(raw: str):
    """ConvoKit utterances.jsonl: {id, text, reply_to, ...}. Pair each utterance with the turn it
    replies to -> a real adjacency pair (A said, B replied) = conversational turn-taking."""
    by_id: dict[str, str] = {}
    rows = []
    for line in raw.splitlines():
        try:
            u = json.loads(line)
        except Exception:
            continue
        t = " ".join((u.get("text") or "").split())
        if t:
            by_id[str(u.get("id"))] = t
        rows.append(u)
    for u in rows:
        # ConvoKit uses the hyphenated key 'reply-to' (fall back to 'reply_to' for other exports)
        parent = by_id.get(str(u.get("reply-to", u.get("reply_to"))))
        child = " ".join((u.get("text") or "").split())
        if parent and child and 6 <= len(parent) <= 400 and 6 <= len(child) <= 400:
            yield {"kind": "register", "source": "wiki_talk", "register": "collab-talk",
                   "text": f"A: {parent}\nB: {child}"}


def parse_stackexchange(raw: str):
    """Stack Exchange Posts.xml: question rows (PostTypeId=1, Title+Body) and answer rows
    (PostTypeId=2, ParentId). Emit question->top-answer pairs as help-register turns."""
    import re as _re
    questions: dict[str, str] = {}
    answers: dict[str, list[tuple[int, str]]] = {}
    for m in _re.finditer(r"<row\b([^>]*)/>", raw):
        attrs = dict(_re.findall(r'(\w+)="([^"]*)"', m.group(1)))
        ptype = attrs.get("PostTypeId")
        if ptype == "1":
            title = _strip_html(attrs.get("Title", ""))
            body = _strip_html(attrs.get("Body", ""))
            q = (title + " " + body).strip()
            if q:
                questions[attrs.get("Id", "")] = q[:400]
        elif ptype == "2":
            pid = attrs.get("ParentId", "")
            body = _strip_html(attrs.get("Body", ""))
            if pid and body:
                answers.setdefault(pid, []).append((int(attrs.get("Score", "0") or 0), body[:400]))
    for qid, q in questions.items():
        ans = sorted(answers.get(qid, []), key=lambda a: -a[0])
        if ans and len(q) >= 10 and len(ans[0][1]) >= 10:
            yield {"kind": "register", "source": "stackexchange", "register": "qa-help",
                   "text": f"A: {q}\nB: {ans[0][1]}"}


def parse_dailydialog(raw: str):
    """DailyDialog dialogues_text.txt: one dialogue per line, turns split by __eou__."""
    for line in raw.splitlines():
        turns = [t.strip() for t in line.split("__eou__") if t.strip()]
        if len(turns) < 2:
            continue
        for i in range(1, len(turns)):
            yield {"kind": "register", "source": "dailydialog", "register": "daily-social",
                   "text": f"A: {turns[i-1]}\nB: {turns[i]}"}


def parse_wizard_of_wikipedia(raw: str):
    """WoW json: list of dialogs; each dialog has 'dialog' turns; a wizard turn carries the grounding
    'checked_sentence'. We emit (knowledge, history, response) grounded pairs — our exact task."""
    data = json.loads(raw)
    for dlg in data if isinstance(data, list) else []:
        history: list[str] = []
        for turn in dlg.get("dialog", []):
            text = (turn.get("text") or "").strip()
            speaker = str(turn.get("speaker", ""))
            checked = turn.get("checked_sentence") or {}
            know = ""
            if isinstance(checked, dict):
                vals = [v for v in checked.values() if isinstance(v, str) and v and "no_passages" not in v]
                know = vals[0] if vals else ""
            if "Wizard" in speaker and text and know:
                yield {"kind": "grounded", "source": "wizard_of_wikipedia",
                       "knowledge": know, "history": history[-4:], "response": text}
            if text:
                history.append(text)


def parse_generic_turns(raw: str, source: str, register: str):
    """Fallback for turn-list JSON (PersonaChat/MultiWOZ/Topical-Chat exports normalised upstream to
    {'turns': [...]}); emits register lines. Topical-Chat grounded extraction slots in when its
    per-turn knowledge field is present."""
    data = json.loads(raw)
    convs = data if isinstance(data, list) else data.get("conversations", [])
    for c in convs:
        turns = c.get("turns") or c.get("utterances") or []
        for i in range(1, len(turns)):
            a, b = str(turns[i - 1]), str(turns[i])
            if a and b:
                yield {"kind": "register", "source": source, "register": register,
                       "text": f"A: {a}\nB: {b}"}


_PARSERS = {"dailydialog": parse_dailydialog, "wizard_of_wikipedia": parse_wizard_of_wikipedia,
            "wiki_talk": parse_wiki_talk, "stackexchange": parse_stackexchange}


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    if "--verdict" in sys.argv or len(sys.argv) == 1:
        print("=== dialogue-source verdict (No-LLM + license filters) ===")
        for name, m in SOURCES.items():
            tag = "ADOPT" if m["adopt"] else "REJECT"
            flag = f"  ⚑ {m.get('flag')}" if m.get("flag") else ""
            print(f"  [{tag:6}] {name:22} {m['register']:15} {m['license']}")
            print(f"            {m['note']}{flag}")
        return 0
    src = sys.argv[sys.argv.index("--src") + 1]
    path = Path(sys.argv[sys.argv.index("--path") + 1])
    meta = SOURCES.get(src)
    if not meta:
        print(f"unknown source {src}"); return 1
    if not meta["adopt"]:
        print(f"REFUSED: {src} — {meta['note']}"); return 2
    if not path.exists():
        print(f"raw file missing: {path}"); return 1
    parser = _PARSERS.get(src, lambda r: parse_generic_turns(r, src, meta["register"]))
    reg = gnd = 0
    with OUT_REG.open("a", encoding="utf-8") as fr, OUT_GND.open("a", encoding="utf-8") as fg:
        for rec in parser(path.read_text(encoding="utf-8", errors="ignore")):
            if rec["kind"] == "grounded":
                fg.write(json.dumps(rec, ensure_ascii=False) + "\n"); gnd += 1
            else:
                fr.write(json.dumps(rec, ensure_ascii=False) + "\n"); reg += 1
    print(f"RESULT ingest {{'src': '{src}', 'register_lines': {reg}, 'grounded_pairs': {gnd}}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
