from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
import gzip
import json
from pathlib import Path
import re
import time
from typing import Any, Iterable

from packages.cgsr.cgsr.ingestion.source_reader import clean_source_text, detect_language
from packages.cgsr.cgsr.ingestion.verification_gate import has_mock_signal

from .verified_payload_feeder import stable_hash
from .wikipedia_dump_reader import iter_wikipedia_sentences


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "data" / "cloud_brain" / "approved_payloads" / "public_corpus"
DEFAULT_AUDIT_DIR = PROJECT_ROOT / "data" / "audits" / "public_corpus_builder"
COLLECTOR_VERSION = "public_corpus_shard_builder_v2"

MOJIBAKE_RE = re.compile(r"\ufffd|Ã|Â|â€|占|�")
HTML_RE = re.compile(r"<[A-Za-z/][^>]*>|&(?:nbsp|amp|lt|gt|quot);", re.IGNORECASE)
LIST_TABLE_RE = re.compile(r"^\s*(?:\||!|\*{2,}|[#;:]{2,}|\{\||\|})")
PRIVATE_RE = re.compile(r"\b(private|personal|secret|password|api[_-]?key|payload vault)\b", re.IGNORECASE)
GENERATED_RE = re.compile(r"\b(generated by|assistant answer|chatgpt|model output|llm response)\b", re.IGNORECASE)
EVAL_RE = re.compile(r"\b(eval row|evaluation set|seed 33033|held[- ]out|benchmark answer)\b", re.IGNORECASE)
URL_ONLY_RE = re.compile(r"^\s*(?:https?://|www\.)\S+\s*$", re.IGNORECASE)
WIKITEXT_RE = re.compile(r"\{\{|\}\}|\[\[|\]\]|\{\||\|}|<ref\b|^=+[^=]+=+$", re.IGNORECASE)
MAINTENANCE_RE = re.compile(
    r"\b(this article|this section|citation needed|needs additional citations|stub|may require cleanup)\b",
    re.IGNORECASE,
)

ALLOWED_LICENSE_MARKERS = (
    "cc by-sa",
    "cc-by-sa",
    "cc by ",
    "cc-by ",
    "cc0",
    "public domain",
    "public-domain",
    "open government licence",
    "korea open government license",
)
INPUT_FORMATS = {"auto", "jsonl", "text", "wikipedia_xml"}


def utc_now() -> str:
    """Return a compact UTC timestamp."""

    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


@dataclass(frozen=True)
class PublicCorpusBuilderConfig:
    """Configuration for converting local public corpus files into approved rows."""

    input_file: str
    source_name: str
    license_hint: str
    language: str = "en"
    source_url: str = ""
    input_format: str = "auto"
    reject_unknown_license: bool = True
    output_dir: str = str(DEFAULT_OUTPUT_DIR)
    audit_dir: str = str(DEFAULT_AUDIT_DIR)
    max_rows: int | None = None
    max_seconds: float | None = None
    min_chars: int = 40
    max_chars: int = 700
    min_alpha_ratio: float = 0.55
    dry_run: bool = True
    execute: bool = False
    dedupe_against_dir: str | None = None
    sample_report: int = 10


@dataclass(frozen=True)
class PublicCorpusShardBuildResult:
    """Summary of one public corpus shard builder run."""

    state: str
    mode: str
    rows_read: int
    rows_accepted: int
    rows_rejected: int
    duplicate_rows: int
    rejection_reasons: dict[str, int]
    output_path: str | None = None
    audit_path: str | None = None
    source_mode: str = "local_dump_shard"
    source_type: str = "local_public_corpus_shard"
    production_store_mutated: bool = False
    local_brain_write: bool = False
    external_llm_used: bool = False
    mock_growth: bool = False
    pair_edges_sent: int = 0
    samples: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable result."""

        return asdict(self)


def _license_allowed(value: str) -> bool:
    lowered = str(value or "").casefold()
    return any(marker in lowered for marker in ALLOWED_LICENSE_MARKERS)


def _open_text_lines(path: Path) -> Iterable[str]:
    suffixes = [suffix.lower() for suffix in path.suffixes]
    if suffixes[-1:] == [".gz"] and ".xml" not in suffixes:
        with gzip.open(path, "rt", encoding="utf-8", errors="strict") as handle:
            yield from handle
        return
    with path.open("r", encoding="utf-8", errors="strict") as handle:
        yield from handle


def _detect_input_format(path: Path, configured: str) -> str:
    if configured not in INPUT_FORMATS:
        raise ValueError(f"unsupported input_format: {configured}")
    if configured != "auto":
        return configured
    suffixes = [suffix.lower() for suffix in path.suffixes]
    if ".xml" in suffixes:
        return "wikipedia_xml"
    if ".jsonl" in suffixes:
        return "jsonl"
    return "text"


def _iter_jsonl_or_text_records(path: Path, fallback_license: str, input_format: str) -> Iterable[dict[str, Any]]:
    """Yield line-scoped records from JSONL, text, or gzipped text variants."""

    is_jsonl = input_format == "jsonl"
    for index, line in enumerate(_open_text_lines(path), start=1):
        raw = line.strip()
        if not raw:
            continue
        if is_jsonl:
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError:
                yield {"text": "", "line_number": index, "record_index": index, "parse_error": "invalid_json"}
                continue
            if not isinstance(parsed, dict):
                yield {"text": "", "line_number": index, "record_index": index, "parse_error": "non_object_json"}
                continue
            text = str(parsed.get("text") or parsed.get("sentence") or parsed.get("extract") or parsed.get("body") or "").strip()
            yield {
                "text": text,
                "title": parsed.get("title"),
                "source_url": parsed.get("source_url") or parsed.get("url"),
                "license": parsed.get("license_hint") or parsed.get("license") or fallback_license,
                "language": parsed.get("language"),
                "source_id": parsed.get("source_id"),
                "line_number": index,
                "record_index": index,
                "page_id": parsed.get("page_id"),
                "revision_id": parsed.get("revision_id"),
                "sentence_index": parsed.get("sentence_index"),
            }
        else:
            yield {
                "text": raw,
                "title": None,
                "source_url": None,
                "license": fallback_license,
                "language": None,
                "source_id": None,
                "line_number": index,
                "record_index": index,
                "page_id": None,
                "revision_id": None,
                "sentence_index": index,
            }


def _iter_source_records(config: PublicCorpusBuilderConfig, path: Path, input_format: str) -> Iterable[dict[str, Any]]:
    if input_format == "wikipedia_xml":
        for record in iter_wikipedia_sentences(
            path,
            language=config.language or "en",
            max_rows=config.max_rows,
            min_chars=config.min_chars,
            max_chars=config.max_chars,
        ):
            yield record.to_record() | {
                "line_number": None,
                "record_index": record.sentence_index,
            }
        return
    yield from _iter_jsonl_or_text_records(path, config.license_hint, input_format)


def _alpha_ratio(text: str, language: str) -> float:
    alpha_count = sum(1 for char in text if char.isalpha())
    return alpha_count / max(1, len(text))


def _quality_reasons(
    text: str,
    *,
    license_hint: str,
    language: str,
    min_chars: int,
    max_chars: int,
    min_alpha_ratio: float,
    reject_unknown_license: bool,
) -> list[str]:
    normalized = clean_source_text(text)
    reasons: list[str] = []
    if reject_unknown_license and not _license_allowed(license_hint):
        reasons.append("unknown_license")
    if len(normalized) < min_chars:
        reasons.append("too_short")
    if len(normalized) > max_chars:
        reasons.append("too_long")
    if MOJIBAKE_RE.search(normalized):
        reasons.append("mojibake")
    if HTML_RE.search(text):
        reasons.append("html_residue")
    if LIST_TABLE_RE.search(text):
        reasons.append("table_or_list_residue")
    if WIKITEXT_RE.search(text):
        reasons.append("wikitext_residue")
    if URL_ONLY_RE.search(normalized):
        reasons.append("url_only")
    if MAINTENANCE_RE.search(normalized):
        reasons.append("maintenance_residue")
    if PRIVATE_RE.search(normalized):
        reasons.append("private_marker")
    if re.search(r"[A-Za-z]:\\|/Users/|/home/|\\\\", normalized):
        reasons.append("local_path_leakage")
    if GENERATED_RE.search(normalized):
        reasons.append("generated_marker")
    if EVAL_RE.search(normalized):
        reasons.append("eval_marker")
    if has_mock_signal(normalized, text):
        reasons.append("mock_marker")
    if (language or "en") == "en" and _alpha_ratio(normalized, language) < min_alpha_ratio:
        reasons.append("low_alpha_ratio")
    elif (language or "en") != "en" and _alpha_ratio(normalized, language) < 0.25:
        reasons.append("low_alpha_ratio")
    return reasons


def _load_dedupe_hashes(path: str | None) -> set[str]:
    root = Path(path) if path else None
    if not root or not root.exists():
        return set()
    hashes: set[str] = set()
    for item in root.rglob("*.jsonl"):
        try:
            lines = item.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            continue
        for line in lines:
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            value = row.get("normalized_text_hash")
            if value:
                hashes.add(str(value))
    return hashes


def _approved_row(
    *,
    config: PublicCorpusBuilderConfig,
    record: dict[str, Any],
    normalized: str,
    normalized_hash: str,
    shard_id: str,
    index: int,
    collected_at: str,
) -> dict[str, Any]:
    page_id = record.get("page_id")
    revision_id = record.get("revision_id")
    sentence_index = record.get("sentence_index") or record.get("record_index") or index
    source_id = str(
        record.get("source_id")
        or f"{config.source_name}:{page_id or record.get('line_number') or index}:{revision_id or sentence_index}"
    )
    source_path = str(record.get("source_url") or config.source_url or Path(config.input_file).resolve())
    provenance_hash = stable_hash(
        "local_public_corpus_shard:"
        f"{source_path}:{page_id}:{revision_id}:{sentence_index}:{normalized_hash}"
    )
    raw_text = str(record.get("text") or "")
    language = str(record.get("language") or config.language or detect_language(normalized))
    return {
        "payload_id": f"public_corpus_{provenance_hash[:24]}",
        "source_type": "local_public_corpus_shard",
        "source_mode": "local_dump_shard",
        "source_id": source_id,
        "source_url_or_path": source_path,
        "source_title": str(record.get("title") or config.source_name),
        "license_hint": str(record.get("license") or config.license_hint),
        "language": language,
        "text": raw_text,
        "normalized_text": normalized,
        "raw_text_hash": stable_hash(raw_text),
        "normalized_text_hash": normalized_hash,
        "provenance_hash": provenance_hash,
        "collected_at": collected_at,
        "collector": "public_corpus_shard_builder",
        "collector_version": COLLECTOR_VERSION,
        "is_private": False,
        "is_generated": False,
        "is_eval_row": False,
        "is_mock": False,
        "quality_flags": [],
        "line_number": record.get("line_number"),
        "record_index": int(record.get("record_index") or index),
        "sentence_index": int(sentence_index),
        "page_id": str(page_id) if page_id is not None else None,
        "revision_id": str(revision_id) if revision_id is not None else None,
        "shard_id": shard_id,
        "target_store": "verified_store_v0_candidate",
        "learning_mode": "semantic_graph",
    }


def build_public_corpus_shard(config: PublicCorpusBuilderConfig) -> PublicCorpusShardBuildResult:
    """Build approved candidate-learning JSONL rows from a local public corpus file."""

    input_path = Path(config.input_file)
    started = time.perf_counter()
    mode = "dry_run" if config.dry_run or not config.execute else "execute"
    if not input_path.exists() or not input_path.is_file():
        return PublicCorpusShardBuildResult(
            state="source_file_missing",
            mode=mode,
            rows_read=0,
            rows_accepted=0,
            rows_rejected=1,
            duplicate_rows=0,
            rejection_reasons={"source_file_missing": 1},
        )
    if config.reject_unknown_license and not _license_allowed(config.license_hint):
        return PublicCorpusShardBuildResult(
            state="no_approved_rows",
            mode=mode,
            rows_read=0,
            rows_accepted=0,
            rows_rejected=1,
            duplicate_rows=0,
            rejection_reasons={"unknown_license": 1},
        )
    try:
        input_format = _detect_input_format(input_path, config.input_format)
    except ValueError as exc:
        return PublicCorpusShardBuildResult(
            state="unsupported_input_format",
            mode=mode,
            rows_read=0,
            rows_accepted=0,
            rows_rejected=1,
            duplicate_rows=0,
            rejection_reasons={str(exc): 1},
        )

    seen_hashes = _load_dedupe_hashes(config.dedupe_against_dir)
    accepted_rows: list[dict[str, Any]] = []
    rejected = 0
    duplicate_rows = 0
    reasons: dict[str, int] = {}
    collected_at = utc_now()
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    shard_id = f"{config.source_name}:{stamp}:{stable_hash(str(input_path.resolve()))[:12]}"
    rows_read = 0

    try:
        for record in _iter_source_records(config, input_path, input_format):
            if config.max_seconds is not None and time.perf_counter() - started > float(config.max_seconds):
                break
            if config.max_rows is not None and len(accepted_rows) >= int(config.max_rows):
                break
            rows_read += 1
            if record.get("parse_error"):
                rejected += 1
                reason = str(record["parse_error"])
                reasons[reason] = reasons.get(reason, 0) + 1
                continue
            text = str(record.get("text") or "")
            license_hint = str(record.get("license") or config.license_hint)
            language = str(record.get("language") or config.language or detect_language(text))
            row_reasons = _quality_reasons(
                text,
                license_hint=license_hint,
                language=language,
                min_chars=config.min_chars,
                max_chars=config.max_chars,
                min_alpha_ratio=config.min_alpha_ratio,
                reject_unknown_license=config.reject_unknown_license,
            )
            normalized = clean_source_text(text)
            normalized_hash = stable_hash(normalized)
            if normalized_hash in seen_hashes:
                duplicate_rows += 1
                row_reasons.append("duplicate_normalized_text")
            if row_reasons:
                rejected += 1
                for reason in sorted(set(row_reasons)):
                    reasons[reason] = reasons.get(reason, 0) + 1
                continue
            seen_hashes.add(normalized_hash)
            accepted_rows.append(
                _approved_row(
                    config=config,
                    record=record,
                    normalized=normalized,
                    normalized_hash=normalized_hash,
                    shard_id=shard_id,
                    index=rows_read,
                    collected_at=collected_at,
                )
            )
    except UnicodeDecodeError:
        return PublicCorpusShardBuildResult(
            state="source_decode_failed",
            mode=mode,
            rows_read=rows_read,
            rows_accepted=len(accepted_rows),
            rows_rejected=rejected + 1,
            duplicate_rows=duplicate_rows,
            rejection_reasons={**reasons, "utf8_decode_error": reasons.get("utf8_decode_error", 0) + 1},
        )

    output_path: Path | None = None
    audit_path: Path | None = None
    if mode == "execute" and accepted_rows:
        output_root = Path(config.output_dir)
        output_root.mkdir(parents=True, exist_ok=True)
        output_path = output_root / f"approved_public_corpus_{stamp}.jsonl"
        output_path.write_text(
            "\n".join(json.dumps(row, ensure_ascii=False, sort_keys=True) for row in accepted_rows) + "\n",
            encoding="utf-8",
        )
    result = PublicCorpusShardBuildResult(
        state="payloads_approved" if accepted_rows else "no_approved_rows",
        mode=mode,
        rows_read=rows_read,
        rows_accepted=len(accepted_rows),
        rows_rejected=rejected,
        duplicate_rows=duplicate_rows,
        rejection_reasons=reasons,
        output_path=str(output_path) if output_path else None,
        samples=accepted_rows[: max(0, int(config.sample_report))],
    )
    if mode == "execute":
        audit_root = Path(config.audit_dir)
        audit_root.mkdir(parents=True, exist_ok=True)
        audit_path = audit_root / f"public_corpus_shard_builder_{stamp}.json"
        audit_payload = result.to_dict() | {
            "input_file": str(input_path),
            "source_name": config.source_name,
            "license_hint": config.license_hint,
            "language": config.language,
            "input_format": input_format,
            "output_path": str(output_path) if output_path else None,
        }
        audit_path.write_text(json.dumps(audit_payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        result = PublicCorpusShardBuildResult(**(result.to_dict() | {"audit_path": str(audit_path)}))
    return result


def _parse_bool(value: str) -> bool:
    return str(value).strip().casefold() not in {"0", "false", "no", "off"}


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build approved public corpus payload shards from local files.")
    parser.add_argument("--input-file", required=True)
    parser.add_argument("--source-name", required=True)
    parser.add_argument("--license-hint", required=True)
    parser.add_argument("--language", default="en")
    parser.add_argument("--source-url", default="")
    parser.add_argument("--input-format", default="auto", choices=sorted(INPUT_FORMATS))
    parser.add_argument("--reject-unknown-license", default="true")
    parser.add_argument("--max-rows", type=int, default=None)
    parser.add_argument("--max-seconds", type=float, default=None)
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--dedupe-against-dir", default=None)
    parser.add_argument("--min-chars", type=int, default=40)
    parser.add_argument("--max-chars", type=int, default=700)
    parser.add_argument("--min-alpha-ratio", type=float, default=0.55)
    parser.add_argument("--sample-report", type=int, default=10)
    parser.add_argument("--dry-run", action="store_true", default=False)
    parser.add_argument("--execute", action="store_true", default=False)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint."""

    args = _parse_args(argv)
    config = PublicCorpusBuilderConfig(
        input_file=args.input_file,
        source_name=args.source_name,
        license_hint=args.license_hint,
        language=args.language,
        source_url=args.source_url,
        input_format=args.input_format,
        reject_unknown_license=_parse_bool(args.reject_unknown_license),
        output_dir=args.output_dir,
        max_rows=args.max_rows,
        max_seconds=args.max_seconds,
        min_chars=args.min_chars,
        max_chars=args.max_chars,
        min_alpha_ratio=args.min_alpha_ratio,
        dry_run=True if not args.execute else bool(args.dry_run),
        execute=bool(args.execute),
        dedupe_against_dir=args.dedupe_against_dir,
        sample_report=args.sample_report,
    )
    result = build_public_corpus_shard(config)
    print(json.dumps(result.to_dict(), ensure_ascii=False, indent=2, sort_keys=True))
    return 0 if result.state in {"payloads_approved", "no_approved_rows", "source_file_missing"} else 2


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
