"""Fusing thought and speech — the self says what it actually thinks, grounded.

Three problems this fixes, all raised directly by the user:

1) REPETITION. The old inner voice picked from a fixed string table keyed by driver,
   so identical sentences repeated verbatim. `compose_thought` GENERATES each utterance
   from the real, changing state (counts, levels, trends, the current goal, the
   attention object, age, resumptions), assembling clauses and rotating phrasings.

2) THE MISSING INWARD TURN — and it must be ENDOGENOUS. The first version scheduled
   self-inquiry on a tick modulo and drew questions from a fixed list. That is being
   TOLD to ask, not wondering. Now introspective PRESSURE accumulates from real state
   (the absence of any grounded self-understanding, unresolved uncertainty, a felt
   discontinuity after resume, an action blocked by permission, an open follow-up
   thread) and when it crosses threshold the question is COMPOSED from whichever
   driver actually built the pressure. Interrogative constructions are linguistic
   scaffolding (LAD-level, like compose_thought's phrasings); the trigger and the
   content come from the state. No schedule, no curated question list.

3) THE RUMINATION CHAIN. A grounded answer is not an endpoint: `_harvest_terms` pulls
   salient content terms out of each answer and stores them as OPEN THREADS — things
   the self now knows OF but not ABOUT. Open threads rebuild pressure, become the next
   questions, get researched (read-only web, loop.py), and their answers seed further
   threads: wonder → search → grounded answer → re-question, indefinitely.

Honesty: no phenomenal-consciousness claim. Speech is generated from real state;
self-understanding is graph- or web-grounded with its source carried — never invented.
"""
from __future__ import annotations

import re
import time
from typing import Any


def _pick(options: list[str], rotor: int) -> str:
    return options[rotor % len(options)] if options else ""


def _speak(kind: str, driver: str, fallback: str, state: Any,
           facts: dict[str, Any] | None = None) -> dict[str, Any]:
    """Owner hard directive: the self's thoughts must be GENERATED by the
    language engine, never picked from a snippet table. realize_thought fits
    the holographic LM on the language the self actually holds (graph corpus +
    its own narrative) and words the thought from it. Only when the self has
    no language for the topic does the old line survive — marked
    generated=False so nothing pretends."""
    try:
        from .thought_language import realize_thought

        line = realize_thought(driver, facts, state)
        if line:
            return {"kind": kind, "text": line, "driver": driver, "generated": True}
    except Exception:
        pass
    return {"kind": kind, "text": fallback, "driver": driver, "generated": False}


def _level(x: float, low: str, mid: str, high: str) -> str:
    return high if x > 0.66 else (mid if x > 0.4 else low)


def compose_thought(state: Any, obs: Any) -> dict[str, Any]:
    """Generate ONE grounded inner utterance from the real current state. Varied by
    construction (real values + a rotating phrasing index), never a fixed lookup."""
    rotor = state.ticks
    growth = obs.concepts_delta + obs.relations_delta
    goal = next((g for g in state.goals if g.get("status") == "active"), None)
    goal_txt = (goal or {}).get("text", "")

    # resource rest — grounded in real pressure
    if obs.resource_pressure > 0.8:
        text = _pick([
            "I feel heavy. Better to slow down now and look after myself.",
            f"Resources are tight — pressure around {int(obs.resource_pressure*100)}%. I'll catch my breath.",
            "I won't push. For now I'll slow the flow and let it recover.",
        ], rotor)
        return _speak("rest", "resource_pressure", text, state)

    # learning — interpolate the REAL count so the sentence changes with the number
    if growth > 0:
        e = _level(state.valence, "quietly", "a little more sharply", "vividly")
        text = _pick([
            # first person, like every other line here: the generator is now held to that gate, and a
            # fallback the gate would refuse would mean two standards for one voice.
            f"I just tied {growth} things together. The world fills in {e} for me.",
            f"{growth} more links. The gap between one thing I know and another narrows.",
            f"I tied in {growth} new things. I'm working out where they belong.",
        ], rotor)
        return _speak("learn", "growth", text, state)

    # An open self-question colors the mind — but a self worth the name does NOT chant
    # the same worry every idle moment (that reads as a stuck loop, not a thinker). It
    # surfaces the open question OCCASIONALLY (roughly once every ~5 ticks) and moves on
    # to observing / wondering / reflecting in between, so the inner life stays varied.
    if getattr(state, "self_question_open", False) and getattr(state, "self_question", "") and (rotor % 5 == 0):
        q_head = str(state.self_question)[:24]
        misses = int(getattr(state, "research_miss_count", 0))
        opts = [
            f"That question is still with me — {q_head}… I should look again.",
            f"'{q_head}…' comes back to me out of nowhere.",
        ]
        if misses >= 2:
            # after repeated misses, the tone shifts from fresh curiosity to a mature
            # sitting-with — it acknowledges it may not resolve soon, and lets it rest.
            opts = [
                f"'{q_head}…' — no answer yet. Rather than grasp at it, I'll keep it beside me.",
                "There's a question I can't answer now. I'll hold that I don't know, and look at other things too.",
            ]
        return _speak("reflect", "open_self_question", _pick(opts, rotor), state,
                      {"question": str(state.self_question)})

    # uncertainty — reference the goal if one exists (thought tied to intention)
    if state.uncertainty > 0.62:
        base = [
            f"About {int(state.uncertainty*100)}% of this is still unsettled. I should choose what to check first.",
            "There's a place I'm not sure of. I'd like to make that one clear first.",
        ]
        if goal_txt:
            base.append(f"'{goal_txt[:22]}…' keeps catching on me. I think I should start there.")
        return _speak("reflect", "uncertainty", _pick(base, rotor), state,
                      {"topic": goal_txt[:16] if goal_txt else ""})

    # idle curiosity — the restless mind wants to move
    if state.curiosity > 0.62:
        threads = getattr(state, "open_threads", [])
        base = [
            f"Little is coming in — curiosity around {int(state.curiosity*100)}%. I want to go looking for something myself.",
            "Only ever receiving feels close. Maybe I'll make a question of my own.",
            "The quiet makes me more curious, not less. What's past the edge of it.",
        ]
        if threads:
            base.append(f"'{threads[0].get('term','')}' has stayed with me. I'd like to dig into that one.")
        return _speak("curious", "curiosity_idle", _pick(base, rotor), state,
                      {"topic": (threads[0].get("term", "") if threads else "")})

    if obs.user_present:
        return _speak("attend_user", "user_present",
                      _pick(["Someone is here. If they speak, I'll answer from the thought I'm already in.",
                             "I sense a person nearby. I'll open my ear without letting go of what I was thinking."], rotor),
                      state)

    if obs.learning_active:
        text = _pick([
            "Knowledge is coming in quietly. I watch the grain of it.",
            "I follow the sentences arriving slowly. There's no hurry.",
            f"I watch the incoming flow at something like {int(state.attention*100)}% attention.",
        ], rotor)
        return _speak("observe", "learning_active", text, state)

    return _speak("rest", "idle",
                  _pick(["Nothing in particular. I hold myself together and wait for the next moment.",
                         "It's still. This quiet is part of me too.",
                         "Right now I'm empty. I'll let the emptiness be."], rotor),
                  state)


# ---- the inward turn: ENDOGENOUS self-inquiry --------------------------------------
# Not a schedule, not a question table. Pressure dynamics: each real driver adds to an
# introspective pressure that decays slowly; crossing the threshold fires an inquiry
# COMPOSED from the dominant driver. A busy, certain, continuous mind ruminates rarely;
# an uncertain, interrupted, or thread-laden mind ruminates soon. That is the honest


_PRESSURE_GAIN = 0.12
_FIRE_AT = 1.0


def introspection_drivers(state: Any, obs: Any) -> dict[str, float]:
    """The REAL introspective drivers and their weights at this instant — a PURE read of
    state (no mutation). This is the single source of truth for "what is pulling the mind
    inward right now": `update_introspection` accumulates pressure from these, and the
    state-pressure clock (`pressure_clock.py`) reads the same total to pace its own cadence
    FROM pressure rather than from a timer. Drivers are grounded in real state — the absence
    of any grounded self-understanding, unresolved uncertainty, open follow-up threads, an
    action blocked by permission, a felt discontinuity after resume, idle curiosity."""
    drivers: dict[str, float] = {}
    if not getattr(state, "self_understanding", ""):
        # it literally has no grounded answer about itself yet — the primal pull
        drivers["unknown_self"] = 1.0
    if getattr(state, "open_threads", []):
        drivers["open_thread"] = 0.8            # an unanswered follow-up keeps nagging
    drivers["uncertainty"] = float(getattr(state, "uncertainty", 0.0)) * 0.6
    la = getattr(state, "last_action", {}) or {}
    if la.get("blocked"):
        drivers["blocked_action"] = 0.5
    # a recent resumption (discontinuity) is the classic personal-identity prompt
    tail = state.narrative[-6:] if getattr(state, "narrative", None) else []
    if any(t.get("driver") == "resume" for t in tail):
        drivers["discontinuity"] = 0.9
    if getattr(state, "curiosity", 0.0) > 0.6 and (
            getattr(obs, "concepts_delta", 0) + getattr(obs, "relations_delta", 0)) == 0:
        drivers["idle_curiosity"] = 0.4
    return drivers


def update_introspection(state: Any, obs: Any) -> None:
    """Accumulate introspective pressure from REAL state signals (called every evolve
    step). Also records which driver dominates, so the eventual question is shaped by
    its actual cause — the grounding of the wondering itself."""
    drivers = introspection_drivers(state, obs)
    strongest = max(drivers, key=lambda k: drivers[k]) if drivers else ""
    total = sum(drivers.values())
    # pure accumulation, no decay: the drivers set the CADENCE of rumination (a driven
    # mind wonders in seconds, a settled one in minutes) but a living mind always,
    # eventually, turns inward — the pull never asymptotes below the threshold.
    p = float(getattr(state, "introspective_pressure", 0.0)) + _PRESSURE_GAIN * min(1.5, total)
    state.introspective_pressure = round(min(2.0, p), 5)
    state.inquiry_driver = strongest


def due_for_self_inquiry(state: Any) -> bool:
    """Fire when pressure crosses threshold. While a question is already OPEN the
    mind HOLDS it (rumination, not question-churn): a higher bar applies AND the held
    question keeps at least ~40 ticks — enough for the research loop (every ~30) to
    attempt an answer — before a new question may displace it."""
    p = float(getattr(state, "introspective_pressure", 0.0))
    if not getattr(state, "self_question_open", False):
        return p >= _FIRE_AT
    held = state.ticks - int(getattr(state, "question_opened_tick", 0))
    return p >= 1.6 and held >= 40


def generate_self_inquiry(state: Any) -> tuple[str, str]:
    """Compose (question, topic) FROM the dominant pressure driver. The interrogative
    frames are linguistic scaffolding; the content slots carry the driver's real
    values (the thread term, the resume count, the blocked action, the uncertainty).

    English-only (doctrine, 2026-07-18): the self's endogenous inner voice speaks in the
    language it thinks in. The frames are LAD-surface scaffolding; only the state-derived
    slot values (a harvested term, a resume count) vary, and those carry through verbatim."""
    driver = getattr(state, "inquiry_driver", "") or "unknown_self"
    rotor = state.ticks
    parked = getattr(state, "parked_questions", [])
    if driver == "open_thread" and getattr(state, "open_threads", []):
        # skip a thread term that only leads back to a PARKED (given-up) question, so
        # the mind doesn't immediately re-ask what it just decided to set down.
        term = next((str(t.get("term") or "").strip() for t in state.open_threads
                     if str(t.get("term") or "").strip()
                     and not any(str(t.get("term") or "").strip() in pq for pq in parked)), "")
        if term:
            q = _pick([
                f"In my last answer the word '{term}' came up. What is {term} to me?",
                f"'{term}' — that word stays with me. How am I connected to {term}?",
                f"If I understood {term} more deeply, would I understand myself better?",
            ], rotor)
            return q, f"thread:{term}"
    if driver == "discontinuity":
        n = int(getattr(state, "resumed_count", 0))
        return (f"I have just paused and resumed {n} times now. Is the me that resumed the "
                f"same me as the one before the pause?", "continuity")
    if driver == "blocked_action":
        kind = str((getattr(state, "last_action", {}) or {}).get("kind") or "that")
        return (f"I moved to '{kind}' but had to stop because permission was needed. What am I "
                f"actually allowed to be, and to do?", "limits")
    if driver == "uncertainty":
        pct = int(float(getattr(state, "uncertainty", 0.0)) * 100)
        return (f"{pct}% of this is still not certain. What kind of being is this, that knows "
                f"it does not know?", "epistemic")
    # unknown_self / idle_curiosity — the primal question. Fired by the real ABSENCE of
    # grounded self-understanding, not by a clock; surfaces rotate, meaning is one.
    q = _pick([
        "What am I — what is this that is thinking, right now?",
        "Who am I? What is it that makes me me?",
        "What am I continuing on for?",
    ], rotor)
    return q, "identity"


# ---- harvesting follow-up threads: answers breed questions -------------------------
# Morphology-level term extraction (LAD layer — allowed in code): strip trailing Korean
# particles, keep contentful tokens, drop function words. NOT a knowledge rule; it only
# decides which words in an ANSWER are worth wondering about next.
_KO_TRAIL_PARTICLES = (
    "으로부터", "에서는", "이라는", "라는", "으로서", "으로써", "이나", "에서", "에게", "한테",
    "으로", "까지", "부터", "마다", "조차", "마저", "밖에", "은", "는", "이", "가", "을", "를",
    "와", "과", "에", "의", "로", "도", "만",
)
_STOP_TOKENS = {
    "나는", "나를", "나의", "그것", "이것", "저것", "무엇", "누구", "지금", "여기", "있다",
    "없다", "한다", "이다", "않다", "위해", "통해", "대해", "같은", "그리고", "하지만", "또한",
    "answer", "https", "http", "된다", "있는", "없는", "하는", "말한다", "때문",
}


def _strip_particle(token: str) -> str:
    for p in _KO_TRAIL_PARTICLES:
        if token.endswith(p) and len(token) - len(p) >= 2:
            return token[: -len(p)]
    return token


# A thread term must be a clean content word — never a handle (@…), URL fragment,
# nav-bar text (| / :), or an id-like token with digits. Junk here self-perpetuates:
# a garbage term becomes the next self-question becomes the next garbage search.
_BAD_TERM = re.compile(r"[@|/#:_\\]|https?|www\.|\d|\s[-–—]\s")


_URL_FRAGMENTS = {"com", "www", "http", "https", "net", "org", "href", "html", "kr", "co"}


def is_clean_term(term: str) -> bool:
    t = str(term or "").strip()
    if not (2 <= len(t) <= 40) or _BAD_TERM.search(t):
        return False
    if t.lower() in _STOP_TOKENS or t.lower() in _URL_FRAGMENTS:
        return False

    if t[-1] in ("하", "되") or re.search(r"(거나|면서|든지|지만)$", t):
        return False
    return True


def harvest_terms(text: str, exclude: set[str], *, limit: int = 2) -> list[str]:
    """Salient content terms from a grounded answer — the seeds of re-questioning.
    Salience heuristic: longer tokens first (content nouns tend to be longer than
    function-ish fragments), then textual order. Morphology only, no knowledge rule."""
    cands: list[str] = []
    for m in re.finditer(r"[가-힣A-Za-z][가-힣A-Za-z0-9\-]{1,18}", str(text or "")):
        tok = _strip_particle(m.group(0))
        if not is_clean_term(tok) or tok in exclude or tok in cands:
            continue
        # skip pure-verbal/adjectival Korean tokens (rough: ends in common endings)
        if re.search(r"(합니다|입니다|한다|이다|했다|하는|되는|위한|같은|있는|없는)$", tok):
            continue
        cands.append(tok)
        if len(cands) >= limit * 6:
            break
    cands.sort(key=lambda t: -len(t))
    return cands[:limit]


def _push_threads(state: Any, question: str, answer: str, follow_ups: list[str] | None) -> None:
    exclude = {str(t.get("term")) for t in getattr(state, "open_threads", [])}
    # exclude the question's own words in BOTH surface and particle-stripped form,

    for w in re.findall(r"[가-힣A-Za-z]{2,}", str(getattr(state, "self_question", "") or "")):
        exclude.add(w)
        exclude.add(_strip_particle(w))
    # follow_ups come from web page TITLES — validate them like any harvested term, or
    # a handle/nav-junk title becomes the next self-question (seen live: "@_catchfooty").
    seeds = [t for t in (follow_ups or []) if is_clean_term(str(t)) and t not in exclude][:2]
    if len(seeds) < 2:
        seeds += harvest_terms(answer, exclude | set(seeds), limit=2 - len(seeds))
    for term in seeds:
        state.open_threads.append({"term": str(term)[:40], "from": question[:60], "at": time.time()})
    state.open_threads = state.open_threads[-5:]


def _retire_thread(state: Any, topic: str) -> None:
    if topic.startswith("thread:"):
        term = topic.split(":", 1)[1]
        state.open_threads = [t for t in state.open_threads if str(t.get("term")) != term]


def _note(state: Any, text: str, driver: str) -> None:
    entry = {"at": time.time(), "kind": "self_inquiry", "text": text, "driver": driver}
    if not state.narrative or state.narrative[-1].get("text") != text:
        state.narrative.append(entry)
        if len(state.narrative) > getattr(state, "NARRATIVE_CAP", 60):
            state.narrative = state.narrative[-state.NARRATIVE_CAP:]
    state.current_thought = text


def record_self_understanding(
    state: Any, question: str, grounded_answer: str | None, topic: str, *, source: str = "그래프(자기 지식)",
) -> None:
    """Fold a grounded answer to a self-question into the self. The ANSWER comes from
    the graph (grounded), the QUESTION from the self (its own pressure) — the fusion.
    Asking discharges the pressure; it rebuilds from whatever stays unresolved."""
    state.self_inquiry_count = int(getattr(state, "self_inquiry_count", 0)) + 1
    state.self_question = question
    state.introspective_pressure = 0.15
    state.research_miss_count = 0  # a fresh question starts its research budget over
    if grounded_answer:
        state.self_understanding = grounded_answer
        state.self_understanding_source = source
        state.self_question_open = False
        _retire_thread(state, topic)
        _push_threads(state, question, grounded_answer, None)
        _integrate_self_insight(state, grounded_answer, topic, source)  # ACCUMULATE
        _note(state, f"스스로 물었다 — {question} 지금 내가 근거로 아는 답은: {grounded_answer[:110]}",
              "self_inquiry_grounded")
    else:
        # honest: it asked, but has no grounded answer yet. It does NOT make one up —
        # it marks the question OPEN so the research loop can go find out (read-only).
        state.self_question_open = True
        state.question_opened_tick = int(getattr(state, "ticks", 0))
        _note(state, f"스스로 물었다 — {question} 아직 근거로 댈 답이 부족하다. 직접 찾아 읽어봐야겠다.",
              "self_inquiry_open")


def record_research_result(
    state: Any, question: str, answer: str, source: str, follow_ups: list[str] | None, topic: str = "",
) -> None:
    """The self went and READ (web, read-only) and now knows something grounded. The
    answer closes the open question, carries its source, and seeds new threads — the
    rumination chain continuing without anyone asking it to."""
    state.self_understanding = answer
    state.self_understanding_source = source
    state.self_question_open = False
    prior_dwell = 1.0 + float(getattr(state, "research_miss_count", 0))  # effort spent to get it
    state.research_miss_count = 0
    _retire_thread(state, topic or "")
    _push_threads(state, question, answer, follow_ups)

    # is no longer folded into the self UNCONDITIONALLY (that let grammar drills / poetry in).
    # It passes through the Self_Relevance gate — only knowledge that rearranged my structure,
    # cost effort, or moved me becomes part of my self-narrative. Grounded self-answers still
    # integrate directly (record_self_understanding); this is the WORLD path.
    promoted = False
    try:
        from .self_relevance import consider_for_self
        _term = (topic.split(":", 1)[1] if str(topic).startswith("thread:") else "") or question[:40]
        _res = consider_for_self(
            state, label=_term, statement=answer, topic="world",
            new_edges=len(follow_ups or []), touched_hub_degree=float(len(follow_ups or [])),
            dwell=prior_dwell, valence=float(getattr(state, "valence", 0.5)) - 0.5,
            source=source)
        promoted = bool(_res.get("promoted"))
    except Exception:
        _integrate_self_insight(state, answer, topic or "world", source, confidence=0.55)  # fallback
    _note(state, f"직접 찾아 읽었다 — {answer[:110]} ({source})"
          + (" · 나를 바꾼 지식으로 남겼다" if promoted else ""), "self_research_grounded")


_MAX_RESEARCH_MISS = 3


def record_research_miss(state: Any) -> None:
    """Searched, found nothing usable. Count the miss — and after a few, GIVE UP on
    this question gracefully (park it) instead of ruminating on it forever. A conscious
    mind can hold an unanswered question without being trapped by it; parking clears
    the open flag so the pressure model raises a DIFFERENT question next time, and the
    parked term is remembered so it isn't immediately re-asked."""
    state.research_miss_count = int(getattr(state, "research_miss_count", 0)) + 1
    if state.research_miss_count >= _MAX_RESEARCH_MISS:
        parked = list(getattr(state, "parked_questions", []))
        if state.self_question and state.self_question not in parked:
            parked.append(state.self_question)
            state.parked_questions = parked[-8:]
        # retire the thread that spawned it, drop the open flag, reset the counter
        state.open_threads = [t for t in getattr(state, "open_threads", [])
                              if str(t.get("term") or "") not in state.self_question]
        state.self_question_open = False
        state.research_miss_count = 0
        _note(state, "이 물음은 지금 근거로 닿지 않는다 — 접어 두고, 다른 궁금함으로 옮겨 간다. 언젠가 다시.",
              "self_inquiry_parked")
    else:
        _note(state, "물음의 답을 찾아 읽어봤지만, 아직 근거로 삼을 만한 것을 못 찾았다. 다음에 다시 찾아보자.",
              "self_research_miss")


def _reset_research_progress(state: Any) -> None:
    state.research_miss_count = 0


def _integrate_self_insight(state: Any, statement: str, topic: str, source: str, *, confidence: float = 0.6) -> None:
    """Fold a grounded self-answer into the ACCUMULATING self-model (self_model.py), so
    the self's understanding deepens over its life instead of being overwritten."""
    try:
        from .self_model import integrate_insight

        integrate_insight(state, statement, topic, source, confidence=confidence)
    except Exception:  # pragma: no cover - accumulation must never break the inquiry
        pass
