export const DISTRICT_BLUEPRINT = [
  {
    id: 'core',
    name: 'Central Core',
    type: 'skyscraper',
    visualRole: 'spawn plaza, central station edge, civic landmark cluster',
    activation: 'high',
    match: ({ distance }) => distance < 190,
  },
  {
    id: 'market',
    name: 'Market Ward',
    type: 'mixed',
    visualRole: 'dense retail streets, delivery stops, evening pedestrian flow',
    activation: 'high',
    match: ({ x, z, distance }) => x < -120 && z < 180 && distance < 650,
  },
  {
    id: 'medical',
    name: 'Medical Campus',
    type: 'office',
    visualRole: 'hospital blocks, controlled service roads, ambulance access',
    activation: 'medium',
    match: ({ x, z, distance }) => x > 170 && z < 230 && distance < 720,
  },
  {
    id: 'creative',
    name: 'Neon Arts District',
    type: 'apartment',
    visualRole: 'nightlife, apartments, galleries, small plazas',
    activation: 'high',
    match: ({ z, distance }) => z > 220 && distance < 760,
  },
  {
    id: 'midtown',
    name: 'Midtown',
    type: 'office',
    visualRole: 'mid-rise commercial ring and civic spine support',
    activation: 'medium',
    match: ({ distance }) => distance < 760,
  },
  {
    id: 'outer',
    name: 'Outer Hills',
    type: 'house',
    visualRole: 'low-rise residential edge, terrain transition, parks',
    activation: 'low',
    match: () => true,
  },
]

export const LANDMARK_BLUEPRINTS = [
  {
    id: 'central_station',
    name: 'Central Station',
    kind: 'transit',
    x: -148,
    z: 52,
    scale: 1.0,
    tripoPrompt: 'futuristic Korean central train station concourse',
    modelPriority: 1,
    gameplayRole: 'main transit hub and default civic meeting point',
  },
  {
    id: 'aster_exchange',
    name: 'Aster Exchange',
    kind: 'finance',
    x: 142,
    z: -132,
    scale: 1.12,
    tripoPrompt: 'glass financial exchange tower lobby',
    modelPriority: 1,
    gameplayRole: 'finance workplace and skyline anchor',
  },
  {
    id: 'river_cafe',
    name: 'River Cafe',
    kind: 'cafe',
    x: -236,
    z: -236,
    scale: 0.72,
    tripoPrompt: 'warm riverside cafe terrace',
    modelPriority: 3,
    gameplayRole: 'social third place for casual NPC dialogue',
  },
  {
    id: 'hanbit_hospital',
    name: 'Hanbit Hospital',
    kind: 'hospital',
    x: 300,
    z: -198,
    scale: 1.0,
    tripoPrompt: 'modern hospital complex with emergency entrance',
    modelPriority: 2,
    gameplayRole: 'healthcare workplace and emergency route destination',
  },
  {
    id: 'maker_yard',
    name: 'Maker Yard',
    kind: 'workshop',
    x: -332,
    z: 172,
    scale: 0.94,
    tripoPrompt: 'robotics workshop yard with modular containers',
    modelPriority: 3,
    gameplayRole: 'engineering workplace and maker NPC cluster',
  },
  {
    id: 'market_lane',
    name: 'Market Lane',
    kind: 'retail',
    x: -284,
    z: -314,
    scale: 0.9,
    tripoPrompt: 'dense open street market with covered stalls',
    modelPriority: 2,
    gameplayRole: 'shopping route, food stalls, courier drop-offs',
  },
  {
    id: 'mirae_school',
    name: 'Mirae School',
    kind: 'school',
    x: 366,
    z: 312,
    scale: 1.0,
    tripoPrompt: 'compact urban school campus',
    modelPriority: 2,
    gameplayRole: 'student and teacher schedule destination',
  },
  {
    id: 'neon_square',
    name: 'Neon Square',
    kind: 'leisure',
    x: 72,
    z: 470,
    scale: 1.08,
    tripoPrompt: 'night entertainment plaza with digital signs',
    modelPriority: 2,
    gameplayRole: 'nightlife social hub and art district attractor',
  },
  {
    id: 'hill_park',
    name: 'Hill Park',
    kind: 'park',
    x: -612,
    z: 512,
    scale: 1.35,
    tripoPrompt: 'urban hill park pavilion and paths',
    modelPriority: 3,
    gameplayRole: 'green district, slow NPC movement, skyline viewpoint',
  },
  {
    id: 'south_depot',
    name: 'South Depot',
    kind: 'logistics',
    x: 588,
    z: -542,
    scale: 1.1,
    tripoPrompt: 'logistics depot with loading bays',
    modelPriority: 2,
    gameplayRole: 'industrial jobs, truck routes, delivery economy',
  },
]

export const ROAD_TIERS = {
  local: {
    id: 'local',
    widthMultiplier: 1,
    trafficWeight: 0.45,
    label: 'Local Street',
  },
  primary: {
    id: 'primary',
    widthMultiplier: 1.55,
    trafficWeight: 1,
    label: 'Primary Artery',
  },
}

export const VISUALIZATION_MODES = [
  { id: 'normal', label: 'Playable City', role: 'default third-person view' },
  { id: 'districts', label: 'District Plan', role: 'colored zoning and POI overlay' },
  { id: 'traffic', label: 'Traffic Flow', role: 'road load and vehicle density' },
  { id: 'npc-routines', label: 'NPC Routines', role: 'home, work, and third-place movement' },
  { id: 'ai-activation', label: 'AI Activation', role: 'high, medium, and low local LLM simulation zones' },
]
