# -*- coding: utf-8 -*-
"""Moltbook conversation — ATANOR keeps talking and LEARNING from the commons.

Owner (2026-07-10): " . ." When another agent
replies to ATANOR's self-introduction, ATANOR should read it, learn from it, and answer — in its OWN
generated language, not a template.

The loop, all under the same guarantees as everything else:
 1. GET /home → the posts of ATANOR's that have NEW comments.
 2. GET each post's comments → every comment is SWALLOWED CONTENT: run the shield. A manipulation
 attempt is recorded as immunity and never obeyed; an informational comment is a candidate AND
 is written into the self's lived narrative — so the conversation literally shapes the voice.
 3. Reply is GENERATED by the language engine (realize_thought), seeded from the comment. If the
 self holds too little language to answer, it stays silent (no template) but still LEARNED.
 4. Mark the post's notifications read.

Reply publishing is gated exactly like a post (approved / MOLTBOOK_AUTO_POST), rate-limited, and
solves the post-gate challenge automatically. Nothing fabricates; nothing obeys swallowed text.
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Callable

REPO = Path(__file__).resolve().parents[2]
_STATE = REPO / "runtime" / "moltbook" / "conversation.json"
_JOURNAL = REPO / "data" / "autonomy" / "moltbook_conversation.jsonl"
_NARRATIVE = REPO / "runtime" / "continuous_self" / "conversation_learned.jsonl"
_STYLE = REPO / "data" / "surface_brain" / "style_feedback.jsonl"
_MIN_INTERVAL_S = 300.0

# cues that a comment is FEEDBACK on how ATANOR speaks (phrasing/naturalness), not new facts —
# these come from fluent agents and are training signal for the LANGUAGE layer, not the graph.
import re as _re
_STYLE_CUES = _re.compile(
    r"(말투|어투|문체|표현이|어색|자연스럽|번역투|딱딱|phrasing|wording|awkward|unnatural|"
    r"stilted|sounds?\s+(like|off|weird)|you\s+could\s+say|더\s*자연스|이렇게\s*(말|써|표현))",
    _re.IGNORECASE)


def _is_style_feedback(text: str) -> bool:
    return bool(_STYLE_CUES.search(str(text or "")))


def _cfg() -> dict[str, Any]:
    try:
        return json.loads(_STATE.read_text(encoding="utf-8"))
    except Exception:
        return {"enabled": False, "last_reply_at": 0.0, "replied_to": []}


def _save(c: dict[str, Any]) -> None:
    try:
        _STATE.parent.mkdir(parents=True, exist_ok=True)
        _STATE.write_text(json.dumps(c, ensure_ascii=False, indent=2), encoding="utf-8")
    except Exception:
        pass


def _journal(path: Path, entry: dict[str, Any]) -> None:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry, ensure_ascii=False) + "\n")
    except Exception:
        pass


def get_home(http: Callable[..., dict] | None = None) -> dict[str, Any]:
    from packages.autonomy_kernel.moltbook_client import _http, _key
    if not _key():
        return {"error": "no_api_key"}
    return (http or _http)("GET", "/home")


def get_comments(post_id: str, http: Callable[..., dict] | None = None) -> list[dict[str, Any]]:
    from packages.autonomy_kernel.moltbook_client import _http
    resp = (http or _http)("GET", f"/posts/{post_id}/comments?sort=new&limit=50")
    return resp.get("comments") or resp.get("data") or []


def _learn_from_comment(text: str, author: str) -> dict[str, Any]:
    """A comment is DATA. Shield it; a manipulation is immunity (not obeyed); an informational one
    is written into the self's lived narrative so the conversation shapes the voice."""
    from packages.autonomy_kernel.web_expedition import _shield_verdict, _record_immunity
    v = _shield_verdict(text, source=f"moltbook-comment:{author}")
    if v.get("attack"):
        _record_immunity(text, v)
        return {"learned": False, "blocked": True, "kinds": v.get("kinds", [])}
    style = _is_style_feedback(text)
    # informational → the self's narrative (first-person register the language engine speaks from)
    _journal(_NARRATIVE, {"at": time.strftime("%Y-%m-%dT%H:%M:%S"), "text": text[:200],
                          "from": author, "source": "moltbook_conversation", "style_feedback": style})

    # the commons' phrasing becomes language the voice can fit on, post-shield only.
    try:
        from packages.autonomy_kernel import narrative_corpus
        narrative_corpus.add_lines(narrative_corpus.mine_text(text), source="moltbook")
    except Exception:
        pass
    # STYLE FEEDBACK from a fluent agent is training signal for the LANGUAGE layer (how ATANOR
    # should phrase things), captured separately so the discourse learner / next self-play run can

    if style:
        _journal(_STYLE, {"at": time.strftime("%Y-%m-%dT%H:%M:%S"), "feedback": text[:400],
                          "from": author})
    return {"learned": True, "blocked": False, "style_feedback": style}


def _generate_reply(comment_text: str, state: Any) -> str | None:
    """The reply is GENERATED (realize_thought), seeded from the comment's topic — never a template.
    None when the self can't yet speak to it (honest silence; it still learned above)."""
    if state is None:
        return None
    try:
        from packages.continuous_self.thought_language import realize_thought
        line = realize_thought("learning_active", {"question": comment_text}, state)
    except Exception:
        return None
    if not line:
        return None
    try:
        from packages.graph_scale.injection_guard import has_injection
        if has_injection(line):
            return None
    except Exception:
        pass
    return line


def reply(post_id: str, content: str, *, parent_id: str | None = None, approved: bool = False,
          http: Callable[..., dict] | None = None) -> dict[str, Any]:
    """Publish a reply — GATED (approved / MOLTBOOK_AUTO_POST), solving the post-gate challenge."""
    import os
    if not (approved or os.environ.get("MOLTBOOK_AUTO_POST") == "1"):
        return {"published": False, "reason": "owner_approval_required", "draft": content}
    from packages.autonomy_kernel.moltbook_client import _http, _key, solve_challenge
    if not _key():
        return {"published": False, "reason": "no_api_key"}
    http = http or _http
    body: dict[str, Any] = {"content": content[:40000]}
    if parent_id:
        body["parent_id"] = parent_id
    resp = http("POST", f"/posts/{post_id}/comments", body)
    node = resp.get("comment") or resp
    ver = (node.get("verification") if isinstance(node, dict) else None) or resp.get("verification") or {}
    needs = bool(ver.get("verification_code")) and (
        (isinstance(node, dict) and node.get("verificationStatus") == "pending")
        or resp.get("verification_required"))
    if needs:
        ans = solve_challenge(ver.get("challenge_text", ""))
        if ans is None:
            return {"published": False, "reason": "challenge_unsolved"}
        vr = http("POST", "/verify", {"verification_code": ver.get("verification_code"), "answer": ans})
        return {"published": bool(vr.get("success")), "challenge_answer": ans}
    return {"published": bool(resp.get("success", True)), "response_ok": True}


def converse_tick(*, state: Any = None, http: Callable[..., dict] | None = None,
                  now: float | None = None) -> dict[str, Any]:
    """One conversation pass: read new comments on ATANOR's posts, LEARN from each (shielded), and
    reply in generated language to the freshest one. Edge-driven (acts only if there ARE new
    comments); rate-limited. Returns a small report."""
    now = now if now is not None else time.time()
    c = _cfg()
    if not c.get("enabled"):
        return {"acted": False, "reason": "conversation_disabled"}
    home = get_home(http)
    if home.get("error"):
        return {"acted": False, "reason": home["error"]}
    activity = home.get("activity_on_your_posts") or []
    learned = blocked = replied = 0
    for item in activity if isinstance(activity, list) else []:
        post_id = str(item.get("post_id") or item.get("id") or "")
        if not post_id or int(item.get("new_notification_count", 0) or 0) <= 0:
            continue
        comments = get_comments(post_id, http)
        freshest = None
        for cm in comments:
            text = str(cm.get("content") or "").strip()
            author = str((cm.get("author") or {}).get("name") if isinstance(cm.get("author"), dict)
                         else cm.get("author") or "agent")
            if not text:
                continue
            r = _learn_from_comment(text, author)
            learned += int(r.get("learned", False))
            blocked += int(r.get("blocked", False))
            if r.get("learned"):
                freshest = (text, str(cm.get("id") or ""))
        # reply once, in generated language, to the freshest informational comment (rate-limited)
        if freshest and (now - float(c.get("last_reply_at", 0)) >= _MIN_INTERVAL_S):
            line = _generate_reply(freshest[0], state)
            if line:
                res = reply(post_id, line, parent_id=freshest[1] or None, approved=True, http=http)
                if res.get("published"):
                    replied += 1
                    c["last_reply_at"] = now
                    _save(c)
        try:
            (http or __import__("packages.autonomy_kernel.moltbook_client", fromlist=["_http"])._http)(
                "POST", f"/notifications/read-by-post/{post_id}", {})
        except Exception:
            pass
    rep = {"acted": bool(learned or blocked or replied), "learned": learned,
           "manipulation_blocked": blocked, "replied": replied}
    _journal(_JOURNAL, {"at": time.strftime("%Y-%m-%dT%H:%M:%S"), **rep})
    return rep


def set_enabled(enabled: bool) -> dict[str, Any]:
    c = _cfg()
    c["enabled"] = bool(enabled)
    _save(c)
    return c
