# -*- coding: utf-8 -*-
"""Register seed generator (owner 2026-07-13: " self-play , Tatoeba").

The measured gap (corpus-composition-is-the-bottleneck): the voice corpus is 0% English and 0.8%
dialogue, so it can only recite Wikipedia. balanced_draw can't balance registers that don't exist —
so we must SOURCE them. This is the license-safe, no-download bootstrap: genuine conversational-
register Korean and everyday English, generated by composing conversational MOVES with slot variation.

HONESTY: these seeds assert NO world-facts — a line like " ? " or "I usually
wake up early" is a register/language EXEMPLAR (how speech sounds), not a knowledge claim. So they
raise the dialogue/English floor without fabricating anything. This is a bootstrap; the bulk should
still come from real dialogue/English datasets (Tatoeba/subtitles) — this just lets the voice start
learning the two registers it is currently starved of.
"""
from __future__ import annotations

import random

# --- conversational dialogue: moves x slots (questions, reactions, sharing, back-channel).
# ENGLISH ONLY (doctrine 2026-07-18) — the Korean move set this replaced carried the same moves;
# the STRUCTURE (move x slot variety) is what the voice's diet needs, in the language it thinks in.
_TIME = ["today", "yesterday", "these days", "just now", "this weekend", "in the evening",
         "this morning", "at night", "earlier"]
_ACT = ["went for a walk", "read a book", "just rested", "got some work done", "had a coffee",
        "cleaned the place", "met a friend", "watched a movie", "worked out", "stayed home",
        "did the shopping", "took a nap"]
_FEEL = ["a bit tired", "in a good mood", "hungry", "sleepy", "excited", "at ease",
         "a little worn out", "relieved"]
_DIALOGUE_TEMPLATES = [
    lambda r: f"What did you do {r.choice(_TIME)}?",
    lambda r: f"I {r.choice(_ACT)} {r.choice(_TIME)}.",
    lambda r: f"I {r.choice(_ACT)} {r.choice(_TIME)}. How about you?",
    lambda r: f"Have you eaten yet? I {r.choice(_ACT)}.",
    lambda r: f"I have been feeling {r.choice(_FEEL)} lately. How are you?",
    lambda r: "Really? That is honestly amazing.",
    lambda r: "No way — so what happened next?",
    lambda r: "Ah, I see. That could be true.",
    lambda r: "Oh nice, I want to try that too.",
    lambda r: "Hmm, I am not so sure about that.",
    lambda r: f"Right, I am {r.choice(_FEEL)} too.",
    lambda r: "Yes, exactly. That is just the feeling.",
    lambda r: "Are you okay? Do not push yourself.",
    lambda r: "Thank you, that really helps.",
    lambda r: f"I quite like {r.choice(['walking', 'reading', 'resting'])} when I can.",
    lambda r: f"How about {r.choice(['a walk', 'a movie', 'lunch', 'coffee'])} together this weekend?",
    lambda r: "I was curious about that too. What do you think?",
    lambda r: "Can we keep talking about what you said earlier?",
]

# --- everyday English: common moves × slots (fact-free register exemplars) ---
_EN_TIME = ["this morning", "last night", "these days", "over the weekend", "earlier today", "lately"]
_EN_ACT = ["went for a walk", "read a bit", "just relaxed", "had some coffee", "cleaned up",
           "met a friend", "watched a movie", "worked out", "stayed home", "took a nap"]
_EN_FEEL = ["a little tired", "pretty good", "kind of sleepy", "relaxed", "a bit worn out", "happy"]
_ENGLISH_TEMPLATES = [
    lambda r: f"I {r.choice(_EN_ACT)} {r.choice(_EN_TIME)}.",
    lambda r: f"What did you do {r.choice(_EN_TIME)}?",
    lambda r: f"I've been feeling {r.choice(_EN_FEEL)} {r.choice(_EN_TIME)}.",
    lambda r: f"That sounds great, let's do it sometime.",
    lambda r: f"I'm not really sure about that, to be honest.",
    lambda r: f"Oh really? How did that go?",
    lambda r: f"Thanks, that means a lot to me.",
    lambda r: f"It's been raining a lot {r.choice(_EN_TIME)}.",
    lambda r: f"Let's grab {r.choice(['lunch','coffee','dinner'])} {r.choice(_EN_TIME)}.",
    lambda r: f"I usually {r.choice(_EN_ACT)} when I have time.",
    lambda r: f"Honestly, I {r.choice(_EN_ACT)} and it felt nice.",
    lambda r: f"How have you been {r.choice(_EN_TIME)}?",
    lambda r: f"I think I'd rather stay in tonight.",
    lambda r: f"That makes sense, I feel the same way.",
]


def dialogue_seeds(n: int, rng: random.Random | None = None) -> list[str]:
    """n distinct conversational-register English lines (deduped)."""
    rng = rng or random.Random()
    out: set[str] = set()
    tries = 0
    while len(out) < n and tries < n * 12:
        tries += 1
        out.add(rng.choice(_DIALOGUE_TEMPLATES)(rng))
    return list(out)


def english_seeds(n: int, rng: random.Random | None = None) -> list[str]:
    """n distinct everyday-English lines (deduped)."""
    rng = rng or random.Random()
    out: set[str] = set()
    tries = 0
    while len(out) < n and tries < n * 12:
        tries += 1
        out.add(rng.choice(_ENGLISH_TEMPLATES)(rng))
    return list(out)


def generate(n_dialogue: int = 300, n_english: int = 200,
             rng: random.Random | None = None) -> dict[str, list[str]]:
    rng = rng or random.Random()
    return {"dialogue": dialogue_seeds(n_dialogue, rng), "english": english_seeds(n_english, rng)}


def seed_into_corpus(n_dialogue: int = 300, n_english: int = 200,
                     rng: random.Random | None = None) -> dict[str, int]:
    """Feed the seeds into the voice corpus (surface, NOT the answer pack — no P0 exposure). Returns
    how many of each register were actually added (after the corpus quality + dedup gate)."""
    from packages.autonomy_kernel.narrative_corpus import add_lines
    g = generate(n_dialogue, n_english, rng)
    added_d = add_lines(g["dialogue"], source="selfplay_dialogue")
    added_e = add_lines(g["english"], source="seed_english")
    return {"dialogue_added": added_d, "english_added": added_e}
